POST http://localhost:3001/api/tasks
Content-Type: application/json

{
     "content": "please work",
    "status": false,
    "category": "work",
    "date": "45",
    "userId": "61da4af07dee34402e4b3778"
}

